runtime: nodejs20  # or latest available
handlers:
  - url: /(.+\.(js|css|ico|png|jpg|jpeg|webp|svg|json|txt|html))$
    static_files: dist/\1
    upload: dist/(.+\.(js|css|ico|png|jpg|jpeg|webp|svg|json|txt|html))$

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
