# steps:
#   # Install dependencies and build React app
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['install']
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['run', 'build']

#   # Deploy to your GCP service (choose one)
#   ## Option A: App Engine
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['app', 'deploy']

#   ## Option B: Cloud Run
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['run', 'deploy', 'your-service-name', '--image', 'gcr.io/$PROJECT_ID/your-image', '--region', 'us-central1']

#   ## Option C: Compute Engine/VM (manual upload)
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['-m', 'rsync', '-r', 'build/', 'gs://your-bucket-name']

# options:
#   logging: CLOUD_LOGGING_ONLY  # or REGIONAL_USER_OWNED_BUCKET
  




options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install', '--legacy-peer-deps']  # 👈 Add this flag
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']
  # ... rest of your steps

  # Step 2: Build React app
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Step 3: Deploy to GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'build/', 'gs://e-wastemate']  # Your bucket