# steps:
#   # Install dependencies and build React app
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['install']
#   - name: 'gcr.io/cloud-builders/npm'
#     args: ['run', 'build']

#   # Deploy to your GCP service (choose one)
#   ## Option A: App Engine
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['app', 'deploy']

#   ## Option B: Cloud Run
#   - name: 'gcr.io/cloud-builders/gcloud'
#     args: ['run', 'deploy', 'your-service-name', '--image', 'gcr.io/$PROJECT_ID/your-image', '--region', 'us-central1']

#   ## Option C: Compute Engine/VM (manual upload)
#   - name: 'gcr.io/cloud-builders/gsutil'
#     args: ['-m', 'rsync', '-r', 'build/', 'gs://your-bucket-name']

# options:
#   logging: CLOUD_LOGGING_ONLY  # or REGIONAL_USER_OWNED_BUCKET
  

options:
  logging: CLOUD_LOGGING_ONLY  # This is the critical fix

steps:
  # Install and build React
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']

  # Choose ONE deployment option below (A, B, or C)
  ## Option A: App Engine (uncomment if using this)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['app', 'deploy']

  ## Option B: Cloud Run (uncomment if using this)
  # - name: 'gcr.io/cloud-builders/gcloud'
  #   args: ['run', 'deploy', 'your-service-name', '--image', 'gcr.io/$PROJECT_ID/your-image', '--region', 'us-central1']

  ## Option C: Compute Engine (uncomment if using this)
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['-m', 'rsync', '-r', 'build/', 'gs://your-bucket-name']